### ISSUE TITLE
User should be unable to create user with invalid email

### ISSUE THREAD

**Issue by Ana17** [MiluchOK/milkinium-api#4]
**Summary**: user should be unable to create user via POST/https://milkinium-api.herokuapp.com/v1/users with an invalid email, without @ symbol, irrelevant characters (,*?, etc)

**Expected result:** user is able to create users only with emails looking like "john_doe@gmail.com"

**Actual result:** user is able to create users with emails "...", ''blala", etc

**Comment by MiluchOK** [comment]
Fixed
